# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('posted', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('twitter_acount', models.CharField(blank=True, max_length=100)),
                ('resume', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
