# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='twitter_acount',
            new_name='twitter_account',
        ),
    ]
